// ui/src/Config.svelte
<script lang="ts">
    import type { AppConfig } from "$rs/AppConfig";
    import type { Source } from "$rs/Source";
    import { invoke } from "@tauri-apps/api";
    import { listen } from "@tauri-apps/api/event";
    import { sourceTypes } from "./types/source";
    import { getContext, setContext } from "svelte";
    import { configuration } from "./App.svelte";
    import { get } from "svelte/store";
    let config = get(configuration);
    configuration.subscribe((cfg) => {
        config = cfg;
    });
    // $: configuration.set(config);
    const getSrcTypes = (cfg: AppConfig) =>
        cfg.sources.map((src) => Object.keys(src)[0] as keyof Source);

    let srcTypes: (keyof Source)[] = getSrcTypes(config);
    

    const onFormChange = () => {
        invoke("set_config", { appConfig: config });
    };

    const removeSource = (i: number) => {
        const sourcesCopy = config.sources;
        sourcesCopy.splice(i, 1);
        config.sources = sourcesCopy;
        const srcTypesCopy = srcTypes;
        srcTypesCopy.splice(i, 1);
        srcTypes = srcTypesCopy;
        onFormChange();
    };
</script>

<form
    on:change={onFormChange}
    class="card card-compact m-auto bg-base-100 shadow-xl"
    style="width:94%"
>
    <card-body class="card-body">
        <h2 class="card-title">Configuration</h2>
        <collapse class="collapse collapse-arrow">
            <input type="checkbox" />
            <div class="collapse-title text-xl font-medium">Sources</div>
            <div class="collapse-content">
                {#each config.sources as source, i}
                    <div class="input-group max-w-xs">
                        <select
                            class="select select-primary"
                            bind:value={srcTypes[i]}
                        >
                            {#each sourceTypes as sourceType}
                                <option value={sourceType}>{sourceType}</option>
                            {/each}
                        </select>
                        <input
                            type="text"
                            bind:value={source[srcTypes[i]]}
                            class="input input-bordered"
                        />
                        <button
                            class="btn btn-secondary"
                            on:click={() => removeSource(i)}>-</button
                        >
                    </div>
                {/each}
                <button
                    class="btn"
                    on:click={(e) => {
                        e.preventDefault();
                        config.sources = [
                            ...config.sources,
                            { [sourceTypes[0]]: "" },
                        ];
                        srcTypes = [...srcTypes, sourceTypes[0]];
                    }}>Add source</button
                >
            </div>
        </collapse>
        <div class="grid grid-cols-3 gap-4">
            <form-control class="form-control">
                <label for="allow_nsfw" class="label cursor-pointer">
                    <span class="label-text">Allow NSFW</span>
                </label>
                <input
                    id="allow_nsfw"
                    type="checkbox"
                    bind:checked={config.allow_nsfw}
                    class="checkbox"
                />
            </form-control>
            <form-control class="form-control">
                <label for="display_background" class="label cursor-pointer">
                    <span class="label-text">Display background in app</span>
                </label>
                <input
                    id="display_background"
                    type="checkbox"
                    bind:checked={config.display_background}
                    class="checkbox"
                />
            </form-control>
            <form-control class="form-control">
                <label for="theme" class="label">
                    <span class="label-text">Theme</span>
                </label>
                <input
                    id="theme"
                    type="text"
                    bind:value={config.theme}
                    class="input input-bordered w-full max-w-xs"
                />
            </form-control>
            <form-control class="form-control">
                <label for="updateInterval" class="label">
                    <span class="label-text">Interval (secs)</span>
                </label>
                <input
                    id="updateInterval"
                    type="text"
                    value={config.interval.secs +
                        config.interval.nanos / 1000000000}
                    on:change={(e) => {
                        const val = parseFloat(e.currentTarget.value);
                        config.interval.secs = Math.floor(val);
                        config.interval.nanos = Math.floor(
                            (val - config.interval.secs) * 1000000000
                        );
                    }}
                    class="input input-bordered w-full max-w-xs"
                />
            </form-control>
            <form-control class="form-control">
                <label for="folder" class="label">
                    <span class="label-text">Cache directory</span>
                </label>
                <div class="input-group">
                    <input
                        id="folder"
                        type="text"
                        bind:value={config.cache_dir}
                        class="input input-bordered w-full max-w-xs"
                    />
                    <button
                        class="btn"
                        on:click={async (e) => {
                            e.preventDefault();
                            config.cache_dir = await invoke("select_folder");
                            // Manually trigger form change (since an update is done synthetically)
                            onFormChange();
                        }}
                        ><svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            fill={getComputedStyle(document.body).color}
                            viewBox="0 0 24 24"
                            ><path
                                d="M10 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"
                            /></svg
                        ></button
                    >
                </div>
            </form-control>
            <form-control class="form-control">
                <label for="history_amount" class="label">
                    <span class="label-text">Max items in history</span>
                </label>
                <input
                    id="history_amount"
                    type="text"
                    bind:value={config.history_amount}
                    class="input input-bordered w-full max-w-xs"
                />
            </form-control>
            <form-control class="form-control">
                <label for="cache_size" class="label">
                    <span class="label-text">Max cache size</span>
                </label>
                <input
                    id="cache_size"
                    type="text"
                    bind:value={config.cache_size}
                    class="input input-bordered w-full max-w-xs"
                />
            </form-control>
        </div>
    </card-body>
</form>

// ui/src/config/Config.tsx
import { debounce } from "../overrides";
import { appConfig, updateConfig } from "../context/config"
import Sources from "./Sources"
import { AppConfig } from "$rs/AppConfig"
import Range from "../components/Range";
// import LogBehaviour from "./LogBehaviour";
import { log } from "../Log";
import { invoke } from "@tauri-apps/api";
import { AiOutlineFolder } from "solid-icons/ai";
import DurationEditor from "./DurationEditor";
import { ConfigUpdate } from "$rs/ConfigUpdate";
// import { For } from "solid-js";

const update = <Prop extends Exclude<keyof AppConfig, "interval" | "sources">, EventValue,
    Transformer extends ((v: EventValue) => AppConfig[Prop]) | undefined = undefined>
    (prop: Prop, transformer?: Transformer) => {
    return debounce((event: ({ target: { value: undefined extends Transformer ? AppConfig[Prop] : EventValue } }) | AppConfig[Prop]) => {
        let value: AppConfig[Prop];
        if (typeof event === "object" && event !== null && "target" in event) {
            if (transformer) value = transformer(event.target.value as EventValue);
            else value = event.target.value as AppConfig[Prop];
        }
        else value = event;
        updateConfig({ Other: { ...appConfig(), [prop]: value } });
    });
}
export default () => {
    const updateInterval = (v: AppConfig["interval"]) => {
        invoke("update_config", { update: { ChangeInterval: { interval: v } } satisfies ConfigUpdate });
    };
    return <div class="card">
        <form class="card-body" onSubmit={e => { e.preventDefault() }}>
            <Range label="Cache size" value={appConfig().cache_size} max={10000} min={10} unit="MB" onInput={update("cache_size")} />
            <div class="join w-full pr-12">
                <label class="join-item w-full">
                    Change interval:
                    <DurationEditor value={appConfig().interval} onInput={debounce(updateInterval)} />
                </label>
            </div>
            <div class="join">
                <label class="join-item">
                    Theme
                    <input class="input join-item" value={appConfig().theme} onInput={update("theme")} />
                </label>
            </div>
            <div class="join">
                <label class="join-item">
                    Display background
                    <input type="checkbox" class="checkbox mx-2 join-item"
                        checked={appConfig().display_background}
                        onInput={e => update("display_background")(e.target.checked)} />
                </label>
            </div>
            <div class="join">
                <label class="join-item">
                    Plugins directory
                    <input class="join-item input" value={appConfig().plugins_dir ?? undefined} onInput={update("plugins_dir")} />
                    <button class="join-item btn btn-primary" onClick={async () => {
                        log(await invoke("select_folder"), "Info");
                    }}><AiOutlineFolder /></button>
                </label>
            </div>
            <div class="join">
                <label class="join-item">
                    Cache directory
                    <input class="join-item input" value={appConfig().cache_dir ?? undefined} onInput={update("cache_dir")} />
                    <button class="join-item btn btn-primary" onClick={async () => {
                        log(await invoke("select_folder"), "Info");
                    }}><AiOutlineFolder /></button>
                </label>
            </div>
            <div class="join">
                <label class="join-item">
                    Alternative changer command
                    <input class="join-item input" value={appConfig().setter_command ?? ""}
                        onInput={update("setter_command", (cmd: string) => cmd || null)} />
                </label>
            </div>
            {/* <div class="join">
                <label class="join-item">
                    Logging behaviours
                    <For each={[...appConfig()?.logging ?? [], undefined]}>{behaviour =>
                        <LogBehaviour existing={behaviour} />
                    }</For>
                </label>
            </div> */}
            <div class="collapse bg-base-200">
                <input type="checkbox" />
                <div class="collapse-title text-xl font-medium">
                    Sources
                </div>
                <div class="collapse-content"><Sources /></div>
            </div>
        </form>
    </div>
}
