// ui/src/App.tsx
import { invoke } from "@tauri-apps/api";
import Config from "./config/Config";
import Log from "./Log";
import { createEffect, on } from "solid-js";
import { appConfig } from "./context/config";

function App() {
  // Theme control
  createEffect(on(() => appConfig().theme, theme => {
    const root = document.getElementsByTagName("html").item(0);
    if (root) root.dataset.theme = theme;
  }));

  return (
    <>
      <Config />
      <Log />
      <div class="card">
        <div class="card-body">
          <button class="btn btn-primary" onClick={() => invoke("update_wallpaper")}>Update wallpaper</button>
          <button class="btn btn-warning" onClick={() => invoke("exit")}>Quit</button>
        </div>
      </div>
    </>
  )
};

export default App;

// ui/src/App.svelte
<script lang="ts">
  import type { AppConfig } from "$rs/AppConfig";
  import { invoke } from "@tauri-apps/api";
  import Config from "./Config.svelte";
  import type { Wallpaper } from "$rs/Wallpaper";
  const initConfigPromise = invoke<AppConfig>("get_config");
  const queuePromise = invoke<Wallpaper[]>("get_queue");
</script>

<main class="w-screen h-screen">
  {#await initConfigPromise}
    <div>Loading...</div>
  {:then initConfig}
    <Config config={initConfig} />
  {/await}
  <button-group class="btn-group">
    <button class="btn" on:click={() => invoke("cache_queue")}>Cache upcoming</button>
    <button class="btn" on:click={() => invoke("update_wallpaper")}>Update wallpaper</button
    >
    <button class="btn btn-warning" on:click={() => invoke("exit")}>Quit</button>
  </button-group>
</main>
